CC = gcc
CFLAGS = -g -Wall

all: artificial_mail 

artificial_mail:
	$(CC) $(CflagsS) -c artificial_mail.c -o artificial_mail.o
	$(CC) $(CflagsS) artificial_mail.o -o artificial_mail

clean:
	rm *.o artificial_mail